/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    useCookies?: boolean;
                    useSessionCookies?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/confirmEmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MapIdentityApi-/api/auth/confirmEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resendConfirmationEmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResendConfirmationEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgotPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resetPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/manage/2fa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TwoFactorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TwoFactorResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/manage/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InfoResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InfoRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InfoResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    language?: string;
                    search?: string;
                    fromYear?: number | string;
                    toYear?: number | string;
                    tag?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntryListItemResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    language?: string;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntryDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    language?: string;
                    group?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagListItemResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    language?: string;
                    search?: string;
                    fromYear?: number | string;
                    toYear?: number | string;
                    tag?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MapEntryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    language?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimePeriodListItemResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    language?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminEntryListItemResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntryUpsertRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceCreatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    language?: string;
                };
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminEntryDetailResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntryUpsertRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries/{entryId}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntryImageRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceCreatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries/{entryId}/audio-tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntryAudioTrackRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceCreatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries/{entryId}/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntryPlaceRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceCreatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries/{entryId}/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntryRouteRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceCreatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries/{entryId}/routes/{routeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                    routeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntryRouteRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                    routeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries/{entryId}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntryRelationshipRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceCreatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries/{entryId}/relationships/{relationshipId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                    relationshipId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntryRelationshipRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                    relationshipId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries/{entryId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntrySourceRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceCreatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries/{entryId}/sources/{sourceId}/{supportsField}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                    sourceId: string;
                    supportsField: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntrySourceRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                    sourceId: string;
                    supportsField: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/time-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    language?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimePeriodListItemResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminTimePeriodUpsertRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceCreatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/time-periods/{timePeriodId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    timePeriodId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminTimePeriodUpsertRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    language?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TagListItemResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminTagUpsertRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceCreatedResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminTagUpsertRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/entries/{entryId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminEntryTagRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/imports/workbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    publishImportedEntries?: boolean;
                    updateExistingRows?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkbookImportResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessTokenResponse: {
            tokenType?: null | string;
            accessToken: string;
            /** Format: int64 */
            expiresIn: number | string;
            refreshToken: string;
        };
        AdminEntryAudioTrackRequest: {
            kind: components["schemas"]["AudioKind"];
            storageProvider: components["schemas"]["StorageProvider"];
            storageKey: null | string;
            publicUrl: null | string;
            mediaType: null | string;
            /** Format: int32 */
            durationSeconds: null | number | string;
            /** Format: int32 */
            sortOrder: number | string;
            isPrimary: boolean;
            languageCode: null | string;
            title: null | string;
            transcript: null | string;
            attribution: null | string;
            license: null | string;
            sourceUrl: null | string;
        };
        AdminEntryDetailResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            status: string;
            kind: string;
            realityStatus: string;
            title: string;
            languageCode: null | string;
            summary: null | string;
            description: null | string;
            whyItMatters: null | string;
            datingNote: null | string;
            dateLabel: null | string;
            /** Format: int64 */
            startYear: null | number | string;
            /** Format: uint8 */
            startMonth: null | number | string;
            /** Format: uint8 */
            startDay: null | number | string;
            /** Format: int64 */
            endYear: null | number | string;
            /** Format: uint8 */
            endMonth: null | number | string;
            /** Format: uint8 */
            endDay: null | number | string;
            timePrecision: null | string;
            timeConfidence: null | string;
            /** Format: uuid */
            primaryTimePeriodId: null | string;
            sourceSheet: null | string;
            /** Format: int32 */
            sourceRow: null | number | string;
            routes: components["schemas"]["EntryRouteResponse"][];
            relationships: components["schemas"]["AdminEntryRelationshipResponse"][];
            sources: components["schemas"]["EntrySourceResponse"][];
        };
        AdminEntryImageRequest: {
            kind: components["schemas"]["ImageKind"];
            storageProvider: components["schemas"]["StorageProvider"];
            storageKey: null | string;
            publicUrl: null | string;
            mediaType: null | string;
            /** Format: int32 */
            width: null | number | string;
            /** Format: int32 */
            height: null | number | string;
            /** Format: int32 */
            sortOrder: number | string;
            isPrimary: boolean;
            attribution: null | string;
            license: null | string;
            sourceUrl: null | string;
            languageCode: null | string;
            altText: null | string;
            caption: null | string;
        };
        AdminEntryListItemResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            status: string;
            kind: string;
            title: string;
            sourceSheet: null | string;
            /** Format: int32 */
            sourceRow: null | number | string;
        };
        AdminEntryPlaceRequest: {
            name: string;
            slug: null | string;
            languageCode: null | string;
            placeType: components["schemas"]["PlaceType"];
            role: components["schemas"]["EntryPlaceRole"];
            spatialConfidence: components["schemas"]["SpatialConfidence"];
            /** Format: double */
            longitude: number | string;
            /** Format: double */
            latitude: number | string;
            modernCountryCode: null | string;
            wikidataId: null | string;
            /** Format: int32 */
            geoNamesId: null | number | string;
            /** Format: int32 */
            sortOrder: number | string;
            note: null | string;
        };
        AdminEntryRelationshipRequest: {
            targetEntrySlug: string;
            relationshipType: components["schemas"]["EntryRelationshipType"];
            /** Format: double */
            confidence: null | number | string;
            note: null | string;
        };
        AdminEntryRelationshipResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            targetEntryId: string;
            targetEntrySlug: string;
            targetEntryTitle: string;
            targetEntryKind: string;
            relationshipType: string;
            /** Format: double */
            confidence: null | number | string;
            note: null | string;
        };
        AdminEntryRoutePointRequest: {
            name: string;
            slug: null | string;
            placeType: components["schemas"]["PlaceType"];
            spatialConfidence: components["schemas"]["SpatialConfidence"];
            role: components["schemas"]["RoutePointRole"];
            /** Format: double */
            longitude: number | string;
            /** Format: double */
            latitude: number | string;
            modernCountryCode: null | string;
            wikidataId: null | string;
            /** Format: int32 */
            geoNamesId: null | number | string;
            /** Format: int32 */
            sortOrder: number | string;
            dateLabel: null | string;
            note: null | string;
        };
        AdminEntryRouteRequest: {
            name: string;
            routeType: components["schemas"]["RouteType"];
            spatialConfidence: components["schemas"]["SpatialConfidence"];
            sourceNote: null | string;
            languageCode: null | string;
            points: components["schemas"]["AdminEntryRoutePointRequest"][];
        };
        AdminEntrySourceRequest: {
            url: string;
            title: null | string;
            publisher: null | string;
            languageCode: null | string;
            supportsField: components["schemas"]["SourceSupportKind"];
            note: null | string;
        };
        AdminEntryTagRequest: {
            tagSlug: string;
        };
        AdminEntryUpsertRequest: {
            title: string;
            slug: null | string;
            languageCode: null | string;
            summary: null | string;
            description: null | string;
            whyItMatters: null | string;
            datingNote: null | string;
            kind: components["schemas"]["EntryKind"];
            status: components["schemas"]["ContentStatus"];
            realityStatus: components["schemas"]["RealityStatus"];
            dateLabel: null | string;
            /** Format: int64 */
            startYear: null | number | string;
            /** Format: uint8 */
            startMonth: null | number | string;
            /** Format: uint8 */
            startDay: null | number | string;
            /** Format: int64 */
            endYear: null | number | string;
            /** Format: uint8 */
            endMonth: null | number | string;
            /** Format: uint8 */
            endDay: null | number | string;
            timePrecision: null | components["schemas"]["TimePrecision"];
            timeConfidence: null | string;
            /** Format: uuid */
            primaryTimePeriodId: null | string;
        };
        AdminTagUpsertRequest: {
            name: string;
            slug: null | string;
            languageCode: null | string;
            tagGroup: string;
            /** Format: uuid */
            parentTagId: null | string;
        };
        AdminTimePeriodUpsertRequest: {
            name: string;
            slug: null | string;
            languageCode: null | string;
            shortDescription: null | string;
            longDescription: null | string;
            periodType: components["schemas"]["TimePeriodType"];
            /** Format: uuid */
            parentPeriodId: null | string;
            /** Format: int64 */
            startYear: null | number | string;
            /** Format: int64 */
            endYear: null | number | string;
            startPrecision: components["schemas"]["TimePrecision"];
            endPrecision: components["schemas"]["TimePrecision"];
            /** Format: int32 */
            sortOrder: number | string;
        };
        /** @enum {unknown} */
        AudioKind: "Narration" | "Summary" | "Pronunciation" | "Ambience" | "Interview" | "Other";
        /** @enum {unknown} */
        ContentStatus: "Draft" | "Published" | "Archived";
        EntryAudioTrackResponse: {
            /** Format: uuid */
            id: string;
            url: string;
            kind: string;
            languageCode: string;
            isPrimary: boolean;
            /** Format: int32 */
            sortOrder: number | string;
            title: null | string;
            transcript: null | string;
            /** Format: int32 */
            durationSeconds: null | number | string;
            attribution: null | string;
            license: null | string;
            sourceUrl: null | string;
        };
        EntryDetailResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            kind: string;
            realityStatus: string;
            title: string;
            summary: null | string;
            description: null | string;
            whyItMatters: null | string;
            datingNote: null | string;
            dateLabel: null | string;
            /** Format: int64 */
            startYear: null | number | string;
            /** Format: uint8 */
            startMonth: null | number | string;
            /** Format: uint8 */
            startDay: null | number | string;
            /** Format: int64 */
            endYear: null | number | string;
            /** Format: uint8 */
            endMonth: null | number | string;
            /** Format: uint8 */
            endDay: null | number | string;
            timePrecision: string;
            timeConfidence: null | string;
            /** Format: uuid */
            primaryTimePeriodId: null | string;
            tags: components["schemas"]["EntryTagResponse"][];
            timePeriods: components["schemas"]["EntryTimePeriodResponse"][];
            places: components["schemas"]["EntryPlaceResponse"][];
            routes: components["schemas"]["EntryRouteResponse"][];
            relatedEntries: components["schemas"]["EntryRelationshipResponse"][];
            sources: components["schemas"]["EntrySourceResponse"][];
            images: components["schemas"]["EntryImageResponse"][];
            audioTracks: components["schemas"]["EntryAudioTrackResponse"][];
        };
        EntryImageResponse: {
            /** Format: uuid */
            id: string;
            url: string;
            kind: string;
            isPrimary: boolean;
            /** Format: int32 */
            sortOrder: number | string;
            altText: null | string;
            caption: null | string;
            attribution: null | string;
            license: null | string;
            sourceUrl: null | string;
        };
        /** @enum {unknown} */
        EntryKind: "Event" | "Invention" | "MythologyEntity" | "MythologyStory" | "Period" | "Discovery" | "Exploration" | "War" | "Civilization" | "Person" | "Place" | "Text" | "Technology" | "ScientificConcept" | "Other";
        EntryListItemResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            kind: string;
            title: string;
            dateLabel: null | string;
            /** Format: int64 */
            startYear: null | number | string;
            /** Format: int64 */
            endYear: null | number | string;
            /** Format: uuid */
            primaryTimePeriodId: null | string;
            primaryImageUrl: null | string;
            primaryAudioUrl: null | string;
        };
        EntryPlaceResponse: {
            /** Format: uuid */
            placeId: string;
            slug: string;
            name: string;
            role: string;
            /** Format: int32 */
            sortOrder: number | string;
            note: null | string;
            placeType: string;
            spatialConfidence: string;
            /** Format: double */
            longitude: null | number | string;
            /** Format: double */
            latitude: null | number | string;
        };
        /** @enum {unknown} */
        EntryPlaceRole: "MainSite" | "Origin" | "Destination" | "Stop" | "Region" | "Birthplace" | "Battlefield" | "CultSite" | "CreatedIn" | "PublishedIn" | "Other";
        EntryRelationshipResponse: {
            /** Format: uuid */
            entryId: string;
            slug: string;
            title: string;
            kind: string;
            relationshipType: string;
            direction: string;
            /** Format: double */
            confidence: null | number | string;
            note: null | string;
        };
        /** @enum {unknown} */
        EntryRelationshipType: "Caused" | "Influenced" | "Preceded" | "Followed" | "PartOf" | "HasPart" | "RelatedTo" | "Contradicts" | "SameTraditionAs" | "LocatedWithin" | "DerivedFrom" | "Other";
        EntryRouteResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            routeType: string;
            spatialConfidence: string;
            sourceNote: null | string;
            geometry: components["schemas"]["GeoCoordinateResponse"][];
            points: components["schemas"]["RoutePointResponse"][];
        };
        EntrySourceResponse: {
            /** Format: uuid */
            sourceId: string;
            url: string;
            title: null | string;
            publisher: null | string;
            languageCode: null | string;
            supportsField: string;
            note: null | string;
        };
        EntryTagResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            tagGroup: string;
            name: string;
        };
        EntryTimePeriodResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            relationType: string;
            periodType: string;
            /** Format: int64 */
            startYear: null | number | string;
            /** Format: int64 */
            endYear: null | number | string;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        GeoCoordinateResponse: {
            /** Format: double */
            longitude: number | string;
            /** Format: double */
            latitude: number | string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        /** Format: binary */
        IFormFile: string;
        /** @enum {unknown} */
        ImageKind: "Primary" | "Gallery" | "Map" | "Portrait" | "Artifact" | "Manuscript" | "Symbol" | "Other";
        InfoRequest: {
            newEmail?: null | string;
            newPassword?: null | string;
            oldPassword?: null | string;
        };
        InfoResponse: {
            email: string;
            isEmailConfirmed: boolean;
        };
        LoginRequest: {
            email: string;
            password: string;
            twoFactorCode?: null | string;
            twoFactorRecoveryCode?: null | string;
        };
        MapEntryResponse: {
            /** Format: uuid */
            entryId: string;
            slug: string;
            kind: string;
            title: string;
            dateLabel: null | string;
            /** Format: int64 */
            startYear: null | number | string;
            /** Format: int64 */
            endYear: null | number | string;
            primaryImageUrl: null | string;
            points: components["schemas"]["MapPointResponse"][];
            routes: components["schemas"]["MapRouteResponse"][];
        };
        MapPointResponse: {
            /** Format: uuid */
            placeId: string;
            placeSlug: string;
            placeName: string;
            role: string;
            spatialConfidence: string;
            /** Format: double */
            longitude: number | string;
            /** Format: double */
            latitude: number | string;
        };
        MapRouteResponse: {
            /** Format: uuid */
            routeId: string;
            name: string;
            routeType: string;
            spatialConfidence: string;
            geometry: components["schemas"]["GeoCoordinateResponse"][];
        };
        /** @enum {unknown} */
        PlaceType: "City" | "Country" | "Region" | "Site" | "Mountain" | "Ocean" | "River" | "RouteStop" | "MythicPlace" | "Space" | "Continent" | "Other";
        /** @enum {unknown} */
        RealityStatus: "Historical" | "Mythological" | "Legendary" | "Disputed" | "Interpretive" | "Fictional";
        RefreshRequest: {
            refreshToken: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
        };
        ResendConfirmationEmailRequest: {
            email: string;
        };
        ResetPasswordRequest: {
            email: string;
            resetCode: string;
            newPassword: string;
        };
        ResourceCreatedResponse: {
            /** Format: uuid */
            id: string;
            slug: null | string;
        };
        RoutePointResponse: {
            /** Format: uuid */
            placeId: string;
            slug: string;
            name: string;
            role: string;
            /** Format: int32 */
            sortOrder: number | string;
            dateLabel: null | string;
            note: null | string;
            /** Format: double */
            longitude: null | number | string;
            /** Format: double */
            latitude: null | number | string;
        };
        /** @enum {unknown} */
        RoutePointRole: "Start" | "Stop" | "End" | "Summit" | "BaseCamp" | "Approximate" | "Other";
        /** @enum {unknown} */
        RouteType: "Voyage" | "Expedition" | "Migration" | "Conquest" | "Climb" | "TradeRoute" | "Mission" | "Journey" | "Other";
        /** @enum {unknown} */
        SourceSupportKind: "General" | "Date" | "Summary" | "Route" | "Location" | "Relationship" | "Image" | "Audio" | "Translation";
        /** @enum {unknown} */
        SpatialConfidence: "Exact" | "Approximate" | "Regional" | "Disputed" | "Mythic" | "Unknown";
        /** @enum {unknown} */
        StorageProvider: "Local" | "S3" | "AzureBlob" | "ExternalUrl";
        TagListItemResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            tagGroup: string;
            name: string;
            /** Format: uuid */
            parentTagId: null | string;
            /** Format: int32 */
            entryCount: number | string;
        };
        TimePeriodListItemResponse: {
            /** Format: uuid */
            id: string;
            slug: string;
            /** Format: uuid */
            parentPeriodId: null | string;
            periodType: string;
            name: string;
            shortDescription: null | string;
            /** Format: int64 */
            startYear: null | number | string;
            /** Format: int64 */
            endYear: null | number | string;
        };
        /** @enum {unknown} */
        TimePeriodType: "Era" | "Age" | "Dynasty" | "Reign" | "Movement" | "WarPeriod" | "CivilizationPeriod" | "CulturalPeriod" | "GeologicalPeriod" | "Other";
        /** @enum {unknown} */
        TimePrecision: "ExactDate" | "Year" | "Decade" | "Century" | "Millennium" | "Range" | "Approximate" | "Unknown" | null;
        TwoFactorRequest: {
            enable?: null | boolean;
            twoFactorCode?: null | string;
            resetSharedKey?: boolean;
            resetRecoveryCodes?: boolean;
            forgetMachine?: boolean;
        };
        TwoFactorResponse: {
            sharedKey: string;
            /** Format: int32 */
            recoveryCodesLeft: number | string;
            recoveryCodes?: null | string[];
            isTwoFactorEnabled: boolean;
            isMachineRemembered: boolean;
        };
        WorkbookImportResult: {
            /** Format: uuid */
            importBatchId: string;
            /** Format: int32 */
            rowsRead: number | string;
            /** Format: int32 */
            entriesCreated: number | string;
            /** Format: int32 */
            entriesUpdated: number | string;
            warnings: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "MapIdentityApi-/api/auth/confirmEmail": {
        parameters: {
            query: {
                userId: string;
                code: string;
                changedEmail?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
