// <auto-generated />
using System;
using HowDidWeGetHere.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HowDidWeGetHere.Infrastructure.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20260722111345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HowDidWeGetHere.Domain.Actors.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("WikidataId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("actors", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Actors.ActorTranslation", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.HasKey("ActorId", "LanguageCode");

                    b.ToTable("actor_translations", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Actors.EntryActor", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("EntryId", "ActorId", "Role");

                    b.HasIndex("ActorId");

                    b.ToTable("entry_actors", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("DateLabel")
                        .HasColumnType("text");

                    b.Property<string>("DefaultTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<byte?>("EndDay")
                        .HasColumnType("smallint");

                    b.Property<byte?>("EndMonth")
                        .HasColumnType("smallint");

                    b.Property<long?>("EndYear")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrimaryTimePeriodId")
                        .HasColumnType("uuid");

                    b.Property<int>("RealityStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int?>("SourceRow")
                        .HasColumnType("integer");

                    b.Property<string>("SourceSheet")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<byte?>("StartDay")
                        .HasColumnType("smallint");

                    b.Property<byte?>("StartMonth")
                        .HasColumnType("smallint");

                    b.Property<long?>("StartYear")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeConfidence")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("TimePrecision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTimePeriodId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status", "StartYear", "EndYear");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryAudioTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attribution")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("License")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("MediaType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PublicUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Transcript")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntryId", "LanguageCode", "IsPrimary");

                    b.ToTable("entry_audio_tracks", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attribution")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("License")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("MediaType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PublicUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntryId", "IsPrimary");

                    b.ToTable("entry_images", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryImageTranslation", b =>
                {
                    b.Property<Guid>("EntryImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("AltText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Caption")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("EntryImageId", "LanguageCode");

                    b.ToTable("entry_image_translations", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FromEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromEntryId");

                    b.HasIndex("ToEntryId");

                    b.ToTable("entry_relationships", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntrySource", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SupportsField")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.HasKey("EntryId", "SourceId", "SupportsField");

                    b.HasIndex("SourceId");

                    b.ToTable("entry_sources", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryTag", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric");

                    b.HasKey("EntryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("entry_tags", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryTimePeriod", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimePeriodId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric");

                    b.HasKey("EntryId", "TimePeriodId", "RelationType");

                    b.HasIndex("TimePeriodId");

                    b.ToTable("entry_time_periods", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryTranslation", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("DatingNote")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("WhyItMatters")
                        .HasColumnType("text");

                    b.HasKey("EntryId", "LanguageCode");

                    b.ToTable("entry_translations", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.TimePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<int>("EndPrecision")
                        .HasColumnType("integer");

                    b.Property<long?>("EndYear")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentPeriodId")
                        .HasColumnType("uuid");

                    b.Property<int>("PeriodType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScopePlaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StartPrecision")
                        .HasColumnType("integer");

                    b.Property<long?>("StartYear")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntryId")
                        .IsUnique();

                    b.HasIndex("ParentPeriodId");

                    b.HasIndex("ScopePlaceId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("time_periods", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.TimePeriodTranslation", b =>
                {
                    b.Property<Guid>("TimePeriodId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.HasKey("TimePeriodId", "LanguageCode");

                    b.ToTable("time_period_translations", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Imports.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("ImportedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Imports.ImportedRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Warning")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("ImportBatchId", "SheetName", "RowNumber")
                        .IsUnique();

                    b.ToTable("imported_rows", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Places.EntryPlace", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("EntryId", "PlaceId", "Role");

                    b.HasIndex("PlaceId");

                    b.ToTable("entry_places", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Places.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int?>("GeoNamesId")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry");

                    b.Property<string>("ModernCountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("PlaceType")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int>("SpatialConfidence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("WikidataId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Places.PlaceTranslation", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.HasKey("PlaceId", "LanguageCode");

                    b.ToTable("place_translations", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Routes.EntryRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("RouteType")
                        .HasColumnType("integer");

                    b.Property<string>("SourceNote")
                        .HasColumnType("text");

                    b.Property<int>("SpatialConfidence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("entry_routes", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Routes.RoutePoint", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("DateLabel")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("RouteId", "PlaceId", "SortOrder");

                    b.HasIndex("PlaceId");

                    b.ToTable("route_points", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Sources.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Title")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentTagId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("TagGroup")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentTagId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Tags.TagTranslation", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("TagId", "LanguageCode");

                    b.ToTable("tag_translations", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Actors.ActorTranslation", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Actors.Actor", "Actor")
                        .WithMany("Translations")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Actors.EntryActor", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Actors.Actor", "Actor")
                        .WithMany("Entries")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "Entry")
                        .WithMany("Actors")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.Entry", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.TimePeriod", "PrimaryTimePeriod")
                        .WithMany()
                        .HasForeignKey("PrimaryTimePeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrimaryTimePeriod");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryAudioTrack", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "Entry")
                        .WithMany("AudioTracks")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryImage", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "Entry")
                        .WithMany("Images")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryImageTranslation", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.EntryImage", "EntryImage")
                        .WithMany("Translations")
                        .HasForeignKey("EntryImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntryImage");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryRelationship", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "FromEntry")
                        .WithMany("OutgoingRelationships")
                        .HasForeignKey("FromEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "ToEntry")
                        .WithMany("IncomingRelationships")
                        .HasForeignKey("ToEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromEntry");

                    b.Navigation("ToEntry");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntrySource", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "Entry")
                        .WithMany("Sources")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HowDidWeGetHere.Domain.Sources.Source", "Source")
                        .WithMany("Entries")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryTag", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "Entry")
                        .WithMany("Tags")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HowDidWeGetHere.Domain.Tags.Tag", "Tag")
                        .WithMany("Entries")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryTimePeriod", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "Entry")
                        .WithMany("TimePeriods")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HowDidWeGetHere.Domain.Entries.TimePeriod", "TimePeriod")
                        .WithMany("Entries")
                        .HasForeignKey("TimePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("TimePeriod");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryTranslation", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "Entry")
                        .WithMany("Translations")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.TimePeriod", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "Entry")
                        .WithOne()
                        .HasForeignKey("HowDidWeGetHere.Domain.Entries.TimePeriod", "EntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HowDidWeGetHere.Domain.Entries.TimePeriod", "ParentPeriod")
                        .WithMany("Children")
                        .HasForeignKey("ParentPeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HowDidWeGetHere.Domain.Places.Place", "ScopePlace")
                        .WithMany("ScopedTimePeriods")
                        .HasForeignKey("ScopePlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Entry");

                    b.Navigation("ParentPeriod");

                    b.Navigation("ScopePlace");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.TimePeriodTranslation", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.TimePeriod", "TimePeriod")
                        .WithMany("Translations")
                        .HasForeignKey("TimePeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimePeriod");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Imports.ImportedRow", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId");

                    b.HasOne("HowDidWeGetHere.Domain.Imports.ImportBatch", "ImportBatch")
                        .WithMany("Rows")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Places.EntryPlace", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "Entry")
                        .WithMany("Places")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HowDidWeGetHere.Domain.Places.Place", "Place")
                        .WithMany("Entries")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Places.PlaceTranslation", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Places.Place", "Place")
                        .WithMany("Translations")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Routes.EntryRoute", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Entries.Entry", "Entry")
                        .WithMany("Routes")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Routes.RoutePoint", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Places.Place", "Place")
                        .WithMany("RoutePoints")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HowDidWeGetHere.Domain.Routes.EntryRoute", "Route")
                        .WithMany("Points")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Tags.Tag", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Tags.Tag", "ParentTag")
                        .WithMany("Children")
                        .HasForeignKey("ParentTagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTag");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Tags.TagTranslation", b =>
                {
                    b.HasOne("HowDidWeGetHere.Domain.Tags.Tag", "Tag")
                        .WithMany("Translations")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HowDidWeGetHere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HowDidWeGetHere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HowDidWeGetHere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HowDidWeGetHere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Actors.Actor", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.Entry", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("AudioTracks");

                    b.Navigation("Images");

                    b.Navigation("IncomingRelationships");

                    b.Navigation("OutgoingRelationships");

                    b.Navigation("Places");

                    b.Navigation("Routes");

                    b.Navigation("Sources");

                    b.Navigation("Tags");

                    b.Navigation("TimePeriods");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.EntryImage", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Entries.TimePeriod", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Entries");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Imports.ImportBatch", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Places.Place", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("RoutePoints");

                    b.Navigation("ScopedTimePeriods");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Routes.EntryRoute", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Sources.Source", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("HowDidWeGetHere.Domain.Tags.Tag", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Entries");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
